import React,{useEffect,useMemo,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import{DndContext,KeyboardSensor,PointerSensor,closestCenter,useDroppable,useSensor,useSensors,type DragEndEvent}from'@dnd-kit/core';
import{SortableContext,sortableKeyboardCoordinates,useSortable,verticalListSortingStrategy}from'@dnd-kit/sortable';
import{CSS}from'@dnd-kit/utilities';
import{findBlock,useBuilder}from'./store';
import type{AttrSchema,BlockDefinition,BlockVariation,ControlProps,EditorRuntime,InspectorControl,PageBlock,PageContent}from'./types';
import'./style.css';

const controls=new Map<string,InspectorControl>();
const categories=new Map<string,string>();
type PageBuilderApi={registerControl:(type:string,control:InspectorControl)=>void;registerCategory:(slug:string,title:string)=>void};
declare global{interface Window{PageBuilder?:PageBuilderApi}}
window.PageBuilder={registerControl:(type,control)=>controls.set(type,control),registerCategory:(slug,title)=>categories.set(slug,title)};
window.dispatchEvent(new CustomEvent('page-builder:ready',{detail:window.PageBuilder}));

function defaults(fields:Record<string,AttrSchema>={}){return Object.fromEntries(Object.entries(fields).map(([key,s])=>[key,structuredClone(s.default??'')]));}
function BuiltInControl({name,schema,value,onChange,requestMedia}:ControlProps){
 const label=schema.label??name;
 if(schema.type==='select')return <label>{label}<select value={String(value??'')} onChange={e=>{const option=schema.options?.find(o=>String(o)===e.target.value);onChange(option??e.target.value)}}>{schema.options?.map(o=><option key={String(o)} value={String(o)}>{String(o)}</option>)}</select>{schema.help&&<small>{schema.help}</small>}</label>;
 if(schema.type==='boolean')return <label className="check"><input type="checkbox" checked={Boolean(value)} onChange={e=>onChange(e.target.checked)}/>{label}</label>;
 if(schema.type==='textarea')return <label>{label}<textarea value={String(value??'')} onChange={e=>onChange(e.target.value)}/>{schema.help&&<small>{schema.help}</small>}</label>;
 if(schema.type==='number'||schema.type==='range')return <label>{label}<input type={schema.type==='range'?'range':'number'} min={schema.min} max={schema.max} step={schema.step} value={Number(value??0)} onChange={e=>onChange(Number(e.target.value))}/>{schema.type==='range'&&<span>{String(value??0)}</span>}</label>;
 if(schema.type==='repeater'){const items=Array.isArray(value)?value as Array<Record<string,unknown>>:[];return <fieldset className="repeater"><legend>{label}</legend>{items.map((item,index)=><div className="repeater-item" key={index}><div className="repeater-head"><strong>Item {index+1}</strong><button type="button" onClick={()=>onChange(items.filter((_,i)=>i!==index))}>Remove</button></div>{Object.entries(schema.fields??{}).map(([field,fieldSchema])=><Control key={field} name={field} schema={fieldSchema} value={item[field]} onChange={next=>onChange(items.map((current,i)=>i===index?{...current,[field]:next}:current))}/>)}</div>)}<button type="button" onClick={()=>onChange([...items,defaults(schema.fields)])}>+ Add item</button></fieldset>}
 if(schema.type==='image')return <label>{label}<div className="media-control"><input type="url" value={String(value??'')} onChange={e=>onChange(e.target.value)}/>{requestMedia&&<button type="button" onClick={requestMedia}>Browse</button>}</div></label>;
 return <label>{label}<input type={schema.type==='url'?'url':'text'} value={String(value??'')} onChange={e=>onChange(e.target.value)}/>{schema.help&&<small>{schema.help}</small>}</label>;
}
function Control(props:ControlProps){const Custom=controls.get(props.schema.type);return Custom?<Custom {...props}/>:<BuiltInControl {...props}/>}

function ChildDrop({blockId}:{blockId:string}){const dropId=`children:${blockId}`;const{setNodeRef,isOver}=useDroppable({id:dropId});return <div ref={setNodeRef} data-drop-id={dropId} className={`child-drop ${isOver?'over':''}`}>Drop blocks here</div>}
function Tree({blocks,definitions,selectedId,onSelect,onRemove,onDuplicate}:{blocks:PageBlock[];definitions:BlockDefinition[];selectedId:string|null;onSelect:(id:string)=>void;onRemove:(id:string)=>void;onDuplicate:(id:string)=>void}){return <SortableContext items={blocks.map(b=>b.id)} strategy={verticalListSortingStrategy}>{blocks.map(block=><TreeItem key={block.id} block={block} definitions={definitions} selectedId={selectedId} onSelect={onSelect} onRemove={onRemove} onDuplicate={onDuplicate}/>)}</SortableContext>}
function TreeItem({block,definitions,selectedId,onSelect,onRemove,onDuplicate}:{block:PageBlock;definitions:BlockDefinition[];selectedId:string|null;onSelect:(id:string)=>void;onRemove:(id:string)=>void;onDuplicate:(id:string)=>void}){const{attributes,listeners,setNodeRef,transform,transition,isDragging}=useSortable({id:block.id});const def=definitions.find(d=>d.name===block.type);return <div ref={setNodeRef} style={{transform:CSS.Transform.toString(transform),transition,opacity:isDragging?.45:1}} className="tree-node"><div className={`tree-row ${selectedId===block.id?'active':''}`}><button className="drag" {...attributes} {...listeners} aria-label={`Move ${def?.title??block.type}`}>⋮⋮</button><button className="tree-select" onClick={()=>onSelect(block.id)}>{def?.title??block.type}</button><button className="duplicate" onClick={()=>onDuplicate(block.id)} title="Duplicate">⧉</button><button className="remove" onClick={()=>onRemove(block.id)} aria-label="Remove block">×</button></div>{def?.supports?.children&&<div className="tree-children">{block.children?.length?<Tree blocks={block.children} definitions={definitions} selectedId={selectedId} onSelect={onSelect} onRemove={onRemove} onDuplicate={onDuplicate}/>:<ChildDrop blockId={block.id}/>}</div>}</div>}

function Inserter({definitions,onAdd}:{definitions:BlockDefinition[];onAdd:(type:string,variation?:BlockVariation)=>void}){const groups=useMemo(()=>definitions.reduce<Record<string,BlockDefinition[]>>((all,d)=>{(all[d.category||'other']??=[]).push(d);return all},{}),[definitions]);return <div className="inserter"><select defaultValue="" onChange={e=>{if(!e.target.value)return;const[type,varName]=e.target.value.split('::');const def=definitions.find(d=>d.name===type);onAdd(type,def?.variations?.find(v=>v.name===varName));e.target.value=''}}><option value="">+ Add block</option>{Object.entries(groups).map(([category,defs])=><optgroup key={category} label={categories.get(category)??category.replace(/(^|-)(\w)/g,(_,s,c)=>`${s?' ':''}${c.toUpperCase()}`)}>{defs.flatMap(def=>[<option value={def.name} key={def.name}>{def.title}</option>,...(def.variations??[]).map(v=><option value={`${def.name}::${v.name}`} key={`${def.name}:${v.name}`}>{def.title} — {v.title}</option>)])}</optgroup>)}</select></div>}

function EditorApp({root,runtime,initial}:{root:HTMLElement;runtime:EditorRuntime;initial:PageContent}){
 const{content,definitions,selectedId,dirty,past,future,bootstrap,replaceContent,select,addBlock,insertBlock,duplicateBlock,updateAttrs,moveBlock,removeBlock,undo,redo}=useBuilder();
 const[ready,setReady]=useState(false),[error,setError]=useState(''),[clipboard,setClipboard]=useState<PageBlock|null>(null);const iframe=useRef<HTMLIFrameElement>(null);const mediaRequest=useRef<{id:string;field:string}|null>(null);
 const sensors=useSensors(useSensor(PointerSensor,{activationConstraint:{distance:5}}),useSensor(KeyboardSensor,{coordinateGetter:sortableKeyboardCoordinates}));const selected=useMemo(()=>findBlock(content.blocks,selectedId),[content.blocks,selectedId]);const definition=definitions.find(d=>d.name===selected?.type);
 useEffect(()=>{bootstrap(runtime,initial).then(()=>setReady(true)).catch(e=>{setError(e instanceof Error?e.message:'Failed to load builder');setReady(true)})},[]);
 useEffect(()=>{const fn=(e:MessageEvent)=>{if(e.origin!==location.origin)return;if(e.data?.type==='SELECT_BLOCK')select(e.data.blockId);if(e.data?.type==='SET_PAGE_BUILDER_CONTENT'&&e.data.content)replaceContent(e.data.content as PageContent);if(e.data?.type==='PAGE_BUILDER_MEDIA_SELECTED'&&mediaRequest.current&&e.data.url){updateAttrs(mediaRequest.current.id,{[mediaRequest.current.field]:e.data.url});mediaRequest.current=null}};addEventListener('message',fn);return()=>removeEventListener('message',fn)},[replaceContent,select,updateAttrs]);
 useEffect(()=>{const fn=(e:KeyboardEvent)=>{if(!(e.ctrlKey||e.metaKey)||e.altKey)return;const key=e.key.toLowerCase();if(key==='z'&&!e.shiftKey){e.preventDefault();undo()}else if((key==='z'&&e.shiftKey)||key==='y'){e.preventDefault();redo()}else if(key==='d'&&selectedId){e.preventDefault();duplicateBlock(selectedId)}};addEventListener('keydown',fn);return()=>removeEventListener('keydown',fn)},[undo,redo,duplicateBlock,selectedId]);
 useEffect(()=>{if(!ready)return;const timer=setTimeout(async()=>{try{const response=await fetch(runtime.renderPageUrl,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},credentials:'same-origin',body:JSON.stringify(content)});const res=await response.json();if(!response.ok)throw new Error(Object.values(res.errors??{}).flat().join(' ')||res.message||'Preview failed');setError('');iframe.current?.contentWindow?.postMessage({type:'REPLACE_PAGE',html:res.html,assets:res.assets},location.origin)}catch(e){setError(e instanceof Error?e.message:'Preview failed')}},120);return()=>clearTimeout(timer)},[content,ready,runtime.renderPageUrl]);
 useEffect(()=>{if(!ready)return;const event=new CustomEvent('page-builder:change',{detail:{content},bubbles:true});root.dispatchEvent(event);if(window.parent!==window)window.parent.postMessage({type:'PAGE_BUILDER_CHANGE',content},location.origin)},[content,ready,root]);
 const onDragEnd=({active,over}:DragEndEvent)=>{if(over&&active.id!==over.id)moveBlock(String(active.id),String(over.id))};
 const copySelected=async()=>{if(!selected)return;setClipboard(structuredClone(selected));await navigator.clipboard?.writeText(JSON.stringify({pageBuilderBlock:selected}))};
 const paste=async()=>{let block=clipboard;try{const text=await navigator.clipboard?.readText();if(text){const parsed=JSON.parse(text);if(parsed?.pageBuilderBlock)block=parsed.pageBuilderBlock}}catch{}if(block)insertBlock(block,selected&&definition?.supports?.children?selected.id:null)};
 const requestMedia=(field:string)=>{if(!selected)return;mediaRequest.current={id:selected.id,field};const detail={blockId:selected.id,field,value:selected.attrs[field]};root.dispatchEvent(new CustomEvent('page-builder:media-request',{detail,bubbles:true}));if(window.parent!==window)window.parent.postMessage({type:'PAGE_BUILDER_MEDIA_REQUEST',...detail},location.origin)};
 if(!ready)return <div className="loading">Loading page builder…</div>;
 return <main className="pb-editor"><header><strong>Page Builder</strong><span className={dirty?'dirty':''}>{dirty?'Modified':'Ready'}</span><div className="history-controls"><button disabled={!past.length} onClick={undo}>Undo</button><button disabled={!future.length} onClick={redo}>Redo</button></div><button disabled={!selected} onClick={copySelected}>Copy</button><button disabled={!clipboard&&!navigator.clipboard} onClick={paste}>Paste</button><button disabled={!selectedId} onClick={()=>selectedId&&duplicateBlock(selectedId)}>Duplicate</button></header>{error&&<div className="builder-error">{error}</div>}<section className="layout"><aside><h3>Blocks</h3><DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={onDragEnd}><Tree blocks={content.blocks} definitions={definitions} selectedId={selectedId} onSelect={select} onRemove={removeBlock} onDuplicate={duplicateBlock}/></DndContext><Inserter definitions={definitions} onAdd={(type,v)=>addBlock(type,selected&&definition?.supports?.children?selected.id:null,v)}/></aside><div className="preview"><iframe ref={iframe} src={runtime.previewUrl} title="Page builder preview"/></div><aside><h3>Inspector</h3>{selected&&definition?<><div className="inspector-title">{definition.title}</div>{definition.description&&<p className="muted">{definition.description}</p>}{Object.entries(definition.attributes).map(([name,schema])=><Control key={name} name={name} schema={schema} value={selected.attrs[name]} onChange={value=>updateAttrs(selected.id,{[name]:value})} requestMedia={runtime.mediaPicker&&schema.type==='image'?()=>requestMedia(name):undefined}/>)}</>:<p>Select a block</p>}</aside></section></main>
}

function parse<T>(value:string|undefined,fallback:T):T{if(!value)return fallback;try{return JSON.parse(value)as T}catch{return fallback}}
document.querySelectorAll<HTMLElement>('[data-page-builder-root]').forEach(root=>{const runtime=parse<EditorRuntime>(root.dataset.pageBuilderRuntime,{blocksUrl:'/api/page-builder/blocks',renderBlockUrl:'/api/page-builder/render-block',renderPageUrl:'/api/page-builder/render-page',previewUrl:'/page-builder/preview'});const initial=parse<PageContent>(root.dataset.pageBuilderContent,{blocks:[]});createRoot(root).render(<React.StrictMode><EditorApp root={root} runtime={runtime} initial={initial}/></React.StrictMode>)});
